package_rename_config-production:
  android:
    app_name: "KuroX"
    package_name: "com.zcross.kurox"

  ios:
    app_name: "KuroX"
    bundle_name: "KuroX"
    package_name: "com.zcross.kurox"

  macos:
    app_name: "KuroX"
    package_name: "com.zcross.kurox"
    copyright_notice: "Copyright © 2026 Zcross091"

  linux:
    app_name: "KuroX"
    package_name: "com.zcross.kurox"
    exe_name: "kurox"

  windows:
    app_name: "KuroX"
    organization: "zcross091"
    copyright_notice: "Copyright © 2026"
    exe_name: "kurox"

package_rename_config-development:
  android:
    app_name: "KuroX Dev"
    package_name: "com.zcross.kurox.dev"

  ios:
    app_name: "KuroX Dev"
    bundle_name: "KuroX Dev"
    package_name: "com.zcross.kurox.dev"

  macos:
    app_name: "KuroX Dev"
    package_name: "com.zcross.kurox.dev"
    copyright_notice: "Copyright © 2026 Zcross091"

  linux:
    app_name: "KuroX Dev"
    package_name: "com.zcross.kurox.dev"
    exe_name: "kurox-dev"

  windows:
    app_name: "KuroX Dev"
    organization: "zcross091"
    copyright_notice: "Copyright © 2026"
    exe_name: "kurox-dev"